name: urdu_dictionary
description: "Lughat — an offline Urdu ⇄ English dictionary."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  connectivity_plus: ^6.1.4
  flutter_tts: ^4.2.3
  sqflite: ^2.3.0
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/seed_words.json
    - assets/dictionary.json
